### PR TITLE
Better Error Messaging in Droplet Actions

### LINKED ISSUE #928: Improve error message when providing non-numeric droplet id
**Describe the Issue:**

As a new user of `doctl`, I mistakenly tried to use using the droplet's name rather than the id when triggering actions. Since the error isn't clear, it took me longer than I'd like to admit to figure out what I was doing wrong.

For example

```shell
% doctl compute droplet-action power-off not-an-id
Error: strconv.Atoi: parsing "not-an-id": invalid syntax
```

An error such as this would have been helpful:

```shell
% doctl compute droplet-action power-off not-an-id
Error: expected <droplet-id> to be numeric, got "not-an-id"
```

**Environment:**
 - doctl version: doctl version 1.54.0-release
 - OS: macOS Big Sur
 - Installation method: Homebrew

### PR DESCRIPTION
**Pull request by ChiefMateStarbuck**
fixes #928

### CODE REVIEW

File: commands/droplet_actions.go [hunk 1]
```diff
@@ -544,3 +548,15 @@ func RunDropletActionSnapshot(c *CmdConfig) error {
 
 	return performAction(c, fn)
 }
+
+// contextualAtoi cleans the error output of Atoi calls
+func contextualAtoi(s, resource string) (int, error) {
+	n, err := strconv.Atoi(s)
+	if err == nil {
+		return n, nil
```
Comment (scotchneat) [inline commands/droplet_actions.go:556]: You should check if `n` is positive before returning here since the returned error on line 559 indicates a positive integer is expected.

File: commands/droplet_actions.go [hunk 2]
```diff
@@ -544,3 +548,15 @@ func RunDropletActionSnapshot(c *CmdConfig) error {
 
 	return performAction(c, fn)
 }
+
+// contextualAtoi cleans the error output of Atoi calls
+func contextualAtoi(s, resource string) (int, error) {
```
Comment (andrewsomething) [inline commands/droplet_actions.go:553]: Looks like this would be generally useful where ever we're using `strconv.Atoi` with user input. Might make sense to put it somewhere that reflects that. Maybe something like `commands/validations.go`?

File: commands/droplet_actions.go (hunk 1 above)
Comment (scotchneat) [reply commands/droplet_actions.go:556]: I think you can ignore my suggestion as that's not really the scope of the issue reported, and it would make sense to implement that across the entire cli, not just for droplet actions.

Other than @andrewsomething request bellow, I think this looks good.

File: commands/validations.go [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+*/
+
+package commands
+
+import (
+	"fmt"
+	"strconv"
+)
+
+// contextualAtoi cleans the error output of Atoi calls
```
Comment (bentranter) [inline commands/validations.go:21]: This comment needs to start with a capital letter for GoDoc and golint to be happy.
```suggestion
// ContextualAtoi cleans the error output of Atoi calls
```

File: commands/validations.go [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+func ContextualAtoi(s, resource string) (int, error) {
+	n, err := strconv.Atoi(s)
+	if err == nil {
+		return n, nil
```
Comment (bentranter) [inline commands/validations.go:25]: It's worth adding a check that `n` is positive, maybe something like,
```suggestion
		if n < 0 {
		    return 0, fmt.Errorf("expected %d to be a postive integer", n)
		}
		return n, nil
```

**Review by bentranter — CHANGES_REQUESTED** [review]
Two small comments around the `ContextualAtoi` function.

File: commands/validations.go (hunk 3 above)
Comment (ChiefMateStarbuck) [reply commands/validations.go:21]: 🤔  i never receive errors like this on my machine. I'll have to look into that. Thank you!

File: commands/validations.go [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+	"fmt"
+	"strconv"
+)
+
+// ContextualAtoi cleans the error output of Atoi calls
+func ContextualAtoi(s, resource string) (int, error) {
+	n, err := strconv.Atoi(s)
+	if err == nil {
+		if n < 0 {
+		    return 0, fmt.Errorf("expected %d to be a postive integer", n)
```
Comment (bentranter) [inline commands/validations.go:26]: Typo in `postive`, should be `positive`:
```suggestion
		    return 0, fmt.Errorf("expected %d to be a positive integer", n)
```

File: commands/validations.go [hunk 6]
```diff
@@ -0,0 +1,34 @@
...
+		}
+		return n, nil
+	}
+	if _, ok := err.(*strconv.NumError); ok {
+		return 0, fmt.Errorf(`expected %s to be a postive integer, got "%s"`, resource, s)
```
Comment (bentranter) [inline commands/validations.go:31]: Same here:
```suggestion
		return 0, fmt.Errorf(`expected %s to be a positive integer, got "%s"`, resource, s)
```

**Review by bentranter — CHANGES_REQUESTED** [review]
Small typo, after that LGTM

**Comment by ChiefMateStarbuck** [comment]
fixes #932

**Comment by bentranter** [comment]
@ChiefMateStarbuck Since this updates that crypto dependency, could you also update the vendored dependencies? You can do so by running `go mod vendor`.

**Comment by ChiefMateStarbuck** [comment]
> @ChiefMateStarbuck Since this updates that crypto dependency, could you also update the vendored dependencies? You can do so by running `go mod vendor`.

Updated 👍

File: commands/validations.go (hunk 5 above)
Comment (bentranter) [reply commands/validations.go:26]: @ChiefMateStarbuck Not sure if the diff is coming out weird for me or not, but it looks like this typo is still here. Could you fix the typo here as well (assuming it's not already fixed?)

**Review by bentranter — CHANGES_REQUESTED** [review]
I think there's still one typo – could you confirm @ChiefMateStarbuck? Thanks!

**Comment by ChiefMateStarbuck** [comment]
> I think there's still one typo – could you confirm @ChiefMateStarbuck? Thanks!

thought i caught that. Fixed 👍

**Review by bentranter — APPROVED** [review]
LGMT! Thanks @ChiefMateStarbuck!
